---
# tasks file for task7

  - name: Create the LOGGING chain
    shell: iptables -N LOGGING
    # Don't fail 
    ignore_errors: yes

  - name: Setup IPTables logging for dropped incoming packages 1
    iptables:
      chain: INPUT
      action: append
      state: present
      jump: LOGGING
  
  - name:  Setup IPTables logging for dropped incoming packages 2
    iptables:
      chain: LOGGING
      action: append
      state: present
      limit: 2/second
      limit_burst: '20'
      log_prefix: "INPUT-DROP: "
      log_level: 4

  - name: create iptables.conf
    template:
      src: iptables.conf.j2
      dest: /etc/rsyslog.d/iptables.conf

  - name: create file for iptables log
    file:
      path: /var/log/iptables.log
      owner: root
      group: root
      mode: '0600'

  - name: create logrotate for iptables log
    template:
      src: logrotate_iptables.j2
      dest: /etc/logrotate.d/iptables

  - name: restart rsyslog
    service:
      name: rsyslog
      state: restarted

      #  - name: Restart server
      #command: /sbin/shutdown -r +1
      #async: 0
      #poll: 0
      #ignore_errors: true

